---
  - name: Configure docker-compose.yml
    template:
      src: docker-compose.override.yml.j2
      dest: /home/mastodon/live/docker-compose.webapp.yml
    notify: "docker-compose up"
    tags:
      - configure
      - webapp
