---
  - name: Configure docker-compose.override.yml
    template:
      src: docker-compose.override.yml.j2
      dest: /home/mastodon/live/docker-compose.override.yml
    notify: "docker-compose up"
