---
- import_tasks: swap.yml

- name: Set timezone
  timezone:
    name: America/Los_Angeles

- name: Install prometheus node exporter
  package:
    name: prometheus-node-exporter
    state: present

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf
    dest: /root/fzf
    clone: yes
    update: yes

- import_tasks: nvim.yml
