---
# tasks file for yttrx-nvim

- name: Create nvim appimage directory
  file:
    path: /opt/nvim
    state: directory
    mode: 0755

- name: Download neovim appimage from github
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.8.2/nvim.appimage
    dest: /opt/nvim/nvim.appimage

- name: Ensure that nvim.appimage is executable
  file:
    path: /opt/nvim/nvim.appimage
    mode: 0755

- name: Create symlink to nvim.appimage
  file:
    src: /opt/nvim/nvim.appimage
    dest: /usr/local/bin/nvim
    state: link

- name: check if lazy.vim exists
  stat:
    path: /root/.config/nvim
  register: lazyvim_check

- name: Clone lazy.vim for user root
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: /root/.config/nvim
  when: not lazyvim_check.stat.exists

# Needed by lazy.vim
- name: Install unzip
  package:
    name: unzip
    state: present

- name: install clang
  package:
    name: clang
    state: present

- name: install npm
  package:
    name: npm
    state: present

- name: Install python3.10-venv
  package:
    name: python3.10-venv
    state: present
