---
dependencies:
  - role: geerlingguy.docker
  - role: ansible-role-oh-my-zsh
    vars:
      users:
        - username: root
          oh_my_zsh:
            theme: agnoster
            plugins:
              - git
